name: Trigger branch cleanup for WAI-APG site

on:
  delete:
  pull_request_target:
    branches-ignore:
      - "dependabot/**"
    types:
      - closed

jobs:
  cleanup-branch-wai:
    if: ${{ github.event_name == 'delete' && github.event.ref_type == 'branch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm

      - name: Install @octokit/rest
        run: npm install @octokit/rest

      - name: Check if branch is from a fork
        id: check_fork
        run: |
          if [ "${{ github.event.pull_request.head.repo.fork }}" == "true" ]; then
            echo "Branch is from a fork."
            echo "FORK_OWNER=${{ github.event.pull_request.head.repo.owner.login }}" >> $GITHUB_ENV
          else
            echo "Branch is not from a fork."
            echo "FORK_OWNER=${{ github.repository_owner }}" >> $GITHUB_ENV
          fi

      - name: Run wai-trigger-cleanup script
        run: |
          node scripts/wai-trigger-cleanup.js
        env:
          GH_TOKEN: ${{ secrets.W3CGRUNTBOT_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          APG_BRANCH: ${{ github.event.ref }}
          FORK_OWNER: ${{ env.FORK_OWNER }}

  cleanup-pr-wai:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm

      - name: Install @octokit/rest
        run: npm install @octokit/rest

      - name: Check if branch is from a fork
        id: check_fork
        run: |
          if [ "${{ github.event.pull_request.head.repo.fork }}" == "true" ]; then
            echo "Branch is from a fork."
            echo "FORK_OWNER=$FORK_OWNER" >> "$GITHUB_OUTPUT"
          fi

      - name: Run wai-trigger-cleanup script
        run: |
          node scripts/wai-trigger-cleanup.js
        env:
          GH_TOKEN: ${{ secrets.W3CGRUNTBOT_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          APG_BRANCH: ${{ github.head_ref }}
          FORK_OWNER: ${{ steps.check_fork.outputs.FORK_OWNER }}
